#!/usr/bin/env bash

set -e

# Switch to the portal directory.
if [[ -n "$PORTAL2_DIR" ]]; then
    cd "$PORTAL2_DIR"
fi

# Copy the configuration file to the app working directory if necessary.
if [[ -n "$PORTAL2_CONFIG" && -f "$PORTAL2_CONFIG" ]]; then
    cp "$PORTAL2_CONFIG" src/
fi

# Verify that the configuration file is present.
if [[ ! -e "src/config.json" ]]; then
    echo "Missing configuration file: $PORTAL2_DIR/src/config.json" >&2
    exit 1
fi

# Build the app.
npm run build

# Run the app.
npm start
