#!/usr/bin/env node
'use strict'

// Generates migrations/00003_reference_data.up.sql from src/user-properties.json.
//
// The registration form's dropdowns are compiled from user-properties.json, so the
// account_user foreign keys (gender_id, ethnicity_id, ...) reference exactly these ids.
// A fresh database has empty lookup tables (the schema migrations carry no data), which
// makes every registration fail with a foreign-key violation. This emits a data migration
// that seeds those tables with the same ids the form submits.
//
// Regenerate after changing user-properties.json:  node src/scripts/gen_reference_seed.js

const fs = require('fs')
const path = require('path')

const PROPS_PATH = path.join(__dirname, '..', 'user-properties.json')
const OUT_PATH = path.join(__dirname, '..', '..', 'migrations', '00003_reference_data.up.sql')

// Ordered so that account_country is seeded before account_region (region.country_id FK).
const TABLES = [
    { key: 'genders', table: 'account_gender', shape: 'named' },
    { key: 'ethnicities', table: 'account_ethnicity', shape: 'named' },
    { key: 'occupations', table: 'account_occupation', shape: 'named' },
    { key: 'funding_agencies', table: 'account_fundingagency', shape: 'named' },
    { key: 'aware_channels', table: 'account_awarechannel', shape: 'named' },
    { key: 'research_areas', table: 'account_researcharea', shape: 'named' },
    { key: 'countries', table: 'account_country', shape: 'coded' },
    { key: 'regions', table: 'account_region', shape: 'region' },
]

const COLUMNS = {
    named: ['id', 'name', 'created_at', 'updated_at'],
    coded: ['id', 'code', 'name', 'created_at', 'updated_at'],
    region: ['id', 'code', 'name', 'created_at', 'updated_at', 'country_id'],
}

let warnings = 0

// Quote and escape a value for a NOT NULL varchar column; null/undefined becomes ''.
function str(value, ctx) {
    if (value === null || value === undefined) {
        console.warn(`WARN: null/empty value for ${ctx}; coercing to ''`)
        warnings++
        value = ''
    }
    return `'${String(value).replace(/'/g, "''")}'`
}

function int(value, ctx) {
    if (!Number.isInteger(value)) {
        console.warn(`WARN: non-integer ${ctx}: ${JSON.stringify(value)}`)
        warnings++
    }
    return value
}

function rowFor(shape, e) {
    const id = int(e.id, 'id')
    switch (shape) {
        case 'named':
            return `(${id}, ${str(e.name, `name(id=${id})`)}, now(), now())`
        case 'coded':
            return `(${id}, ${str(e.code, `code(id=${id})`)}, ${str(e.name, `name(id=${id})`)}, now(), now())`
        case 'region':
            return `(${id}, ${str(e.code, `code(id=${id})`)}, ${str(e.name, `name(id=${id})`)}, now(), now(), ${int(e.country_id, `country_id(id=${id})`)})`
        default:
            throw new Error(`unknown shape ${shape}`)
    }
}

function main() {
    const props = JSON.parse(fs.readFileSync(PROPS_PATH, 'utf8'))

    const parts = [
        '-- 00003_reference_data.up.sql',
        '-- Generated by src/scripts/gen_reference_seed.js from src/user-properties.json.',
        '-- Do not edit by hand; regenerate instead.',
        '--',
        '-- Seeds the account_* reference/lookup tables that account_user foreign keys',
        '-- reference. Ids match user-properties.json (the compiled registration form).',
        '',
        'SET search_path = public, pg_catalog;',
        '',
        'BEGIN;',
        '',
    ]

    for (const { key, table, shape } of TABLES) {
        const rows = props[key]
        if (!Array.isArray(rows) || rows.length === 0) {
            throw new Error(`user-properties.json key "${key}" is missing or empty`)
        }
        const cols = COLUMNS[shape].join(', ')
        parts.push(`-- ${table}: ${rows.length} rows`)
        parts.push(`INSERT INTO public.${table} (${cols}) VALUES`)
        parts.push(rows.map(e => '    ' + rowFor(shape, e)).join(',\n'))
        parts.push('ON CONFLICT (id) DO NOTHING;')
        parts.push('')
    }

    parts.push('-- Advance each sequence past the seeded ids so app inserts do not collide.')
    for (const { table } of TABLES) {
        parts.push(
            `SELECT pg_catalog.setval('public.${table}_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.${table}), true);`
        )
    }
    parts.push('')
    parts.push('COMMIT;')
    parts.push('')

    fs.writeFileSync(OUT_PATH, parts.join('\n'))
    const total = TABLES.reduce((n, { key }) => n + props[key].length, 0)
    console.log(`Wrote ${OUT_PATH} (${total} rows, ${warnings} warning(s))`)
}

main()
