-- 00004_service_catalog.up.sql
-- Seeds the portal service catalog for the Discovery Environment, DE-VICE, and Data
-- Commons (data store), mirrored from the canonical (QA/prod) rows. Portal service data
-- is Django-era and not otherwise seeded by migrations. Guarded with ON CONFLICT DO
-- NOTHING so it no-ops where the rows already exist (QA/prod) and populates fresh DBs.
-- Service URLs are the canonical cyverse.org ones; api_form.intercom_team_id carries an
-- inert external id (intercom is disabled), and the intercom/form-group link tables are
-- intentionally omitted.

SET search_path = public, pg_catalog;

BEGIN;

-- api_servicemaintainer
INSERT INTO public.api_servicemaintainer ("id", "name", "website_url", "created_at", "updated_at") VALUES ('1', 'CyVerse', 'http://www.cyverse.org', '2016-12-06 13:51:30.653-07', '2016-12-06 13:51:30.653-07') ON CONFLICT ("id") DO NOTHING;

-- api_service (DE=2, DE-VICE=43, Data Commons=3)
INSERT INTO public.api_service ("id", "name", "description", "about", "service_url", "is_public", "icon_url", "created_at", "updated_at", "service_maintainer_id", "approval_key", "subtitle") VALUES ('2', 'Discovery Environment (DE)', 'Use hundreds of bioinformatics apps and manage data in the CyVerse Data Store from a simple web interface', 'By providing a consistent user interface for access to the tools and computing resources needed for specialized scientific analyses, the Discovery Environment facilitates data exploration and scientific discovery.

### KEY FEATURES
* Access tools and data in the DE with an unprecedented degree of scalability due to its integration with CyVerse’s data management system and compute resources. In the future, the DE will employ provenance tracking of both primary and derived files to track and reproduce experiments.
* Run existing bioinformatics software apps on CyVerse clusters or TACC supercomputers quickly, easily, and efficiently. We offer apps for phylogenetics and systematics, data standardization, transcriptomics and genomics, clustering and network analysis, QTL mapping and GWAS, sequence alignments and phylogenetic tree building, NGS, phylogenetic comparative methods, and trait evolution.
* Use hundreds of command-line analytical tools, utility tools, and scripts, without the need to learn the command line.
* Access, manage, and share data files, workflows, analyses results, and data visualizations with collaborators or with the community at large, knowing your data is safe and accessible within the iRODS data management system.
* Use analytical apps individually or in workflows on local or high-performance computing nodes.
* Easily add any command-line tool or any executable into the tool list, and then create or edit a new customized interface for the app or create a sequenced workflow by chaining one app to another in automated workflow.
* Use application programming interfaces (APIs) for tool integration, resource-intensive analyses, or workflow building.
* Use the same login for all CyVerse resources.

Because much of the complexity is hidden from the user, the DE makes it easy for non-technical users to get the job done simply and easily; no need to master command-line analysis tools or learn new software for every type of analysis. All aspects of your bioinformatics workflow—data management, analysis, sharing large datasets, and more—can be handled within the DE.', 'https://de.cyverse.org', 'true', 'de', '2016-12-06 13:51:30.653-07', '2017-05-30 13:47:41.689467-07', '1', 'DISCOVERY_ENVIRONMENT', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_service ("id", "name", "description", "about", "service_url", "is_public", "icon_url", "created_at", "updated_at", "service_maintainer_id", "approval_key", "subtitle") VALUES ('3', 'Data Commons', 'A unified system for managing and sharing your data across CyVerse''s tools and services', 'Based on a technology called iRODS, CyVerse''s easy-to-use data hosting gives you great flexibility and control over your data. Choose from different interfaces—from web services to mountable file systems to high-speed command-line transfers—to connect your data to every CyVerse platform. To learn how to use the Data Store, see Manage Data.

### KEY FEATURES
Hosting your data in CyVerse''s Data Store allows you to:

* Use your preferred access method to upload, download, and access data from your computer to the Data Store.
* Share your data instantly with other users.
* Keep your data secure by setting permissions to keep your data private only to you, share it with specific collaborators, or make it accessible to the general public (so no account is required).
* Take advantage of parallel data transfers for fast uploads and can handle partial transfers—so if a transfer of 1,000 files or one very large file is interrupted, the process can resume in the same place later.

### ACCESS METHODS
There are a number of different ways with which you can upload, import, and download private or public data in the Data Store. Most require a CyVerse account, but you can access public data anonymously using the Mirrors site (below) without an account, if you don''t have one already set up.', 'http://datacommons.cyverse.org', 'true', 'data-store', '2016-12-06 13:51:30.653-07', '2017-05-30 13:47:34.004028-07', '1', 'DATA_COMMONS', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_service ("id", "name", "description", "about", "service_url", "is_public", "icon_url", "created_at", "updated_at", "service_maintainer_id", "approval_key", "subtitle") VALUES ('43', 'DE - VICE', 'Visual Interactive Computing Environment in the Discovery Environment', 'VICE, which stands for Visual Interactive Computing Environment, is a component of the Discovery Environment (DE), CyVerse’s data science workbench. VICE allows users to launch web-based applications (such as Jupyter and RStudio) from the DE. Once an application is launched users can access the VICE app through a linked URL, import data from the CyVerse Data Store into the application, and pull data from anywhere on the web using standard commands (curl, wget, git).', 'https://de.cyverse.org/de/', 'true', 'vice', '2021-03-30 14:07:02.778824-07', '2021-03-30 14:07:02.778824-07', '1', 'VICE', '') ON CONFLICT ("id") DO NOTHING;

-- api_cyverseservice (DE, Data Commons; VICE has no cyverse child)
INSERT INTO public.api_cyverseservice ("service_ptr_id", "approval_request_url", "grant_request_url", "auto_add_new_users", "grant_dag_id", "review_dag_id") VALUES ('2', 'http://localhost:8000/callbacks/approval/discovery-environment/', 'http://localhost:8000/callbacks/grant/discovery-environment/', 'true', '', '') ON CONFLICT ("service_ptr_id") DO NOTHING;
INSERT INTO public.api_cyverseservice ("service_ptr_id", "approval_request_url", "grant_request_url", "auto_add_new_users", "grant_dag_id", "review_dag_id") VALUES ('3', 'http://localhost:8000/callbacks/approval/data-commons/', 'http://localhost:8000/callbacks/grant/data-commons/', 'true', '', '') ON CONFLICT ("service_ptr_id") DO NOTHING;

-- api_accessrequestquestion (VICE)
INSERT INTO public.api_accessrequestquestion ("id", "type", "question", "is_required", "created_at", "updated_at", "service_id") VALUES ('4', 'text', 'Please describe your science use-case. Be as specific about your analysis as possible to help us quickly evaluate your request.', 'true', '2021-04-06 09:07:49.149124-07', '2021-04-06 09:07:49.149124-07', '43') ON CONFLICT ("id") DO NOTHING;

-- api_form
INSERT INTO public.api_form ("id", "name", "created_at", "updated_at", "description", "explanation", "intercom_team_id", "is_public") VALUES ('2', 'Data Store Shared Folder Request', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', 'Request more data storage for a Community Released data folder you own.', 'The default data storage allocation for each CyVerse user is 100GB and is intended for active data being analyzed. Any data you own or share with other users counts towards your allocation, including [Community Released](http://datacommons.cyverse.org/browse/iplant/home/shared) data in folders that you own. Data that others share with you and data published to the [CyVerse Curated](http://datacommons.cyverse.org/browse/iplant/home/shared/commons_repo/curated) folders of the [Data Commons](http://www.cyverse.org/data-commons-user-agreement) are __excluded__ from your allocation.

If you need more data storage for personal or shared use of a folder that already exists (i.e., your home folder or a Community Released data folder you own), complete and submit this form.

If you need an allocation for a new Community Released data folder, please use the [Request for Community Released Data Folder](https://user.cyverse.org/forms/7/overview) form to request an increased allocation when you request the folder.

Information you provide in the form may be included in CyVerse annual reporting of impacts and resource use to our stakeholders.

**Review process:**


* Requests of 100GB -10TB are usually reviewed within two (2) business days (review level 1)
* Requests of >10TB are usually reviewed within two (2) weeks (review level 2)', '1509745', 'false') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_form ("id", "name", "created_at", "updated_at", "description", "explanation", "intercom_team_id", "is_public") VALUES ('7', 'Community Released Data Folder', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', 'Request to release a publicly-accessible data folder for community data.', '[Community Released](http://datacommons.cyverse.org/browse/iplant/home/shared) data folders are intended for collaborative projects that are producing public datasets that are growing or changing frequently, or that do not need long-term preservation. Along with [CyVerse Curated](http://datacommons.cyverse.org/browse/iplant/home/shared/commons_repo/curated), [Community Released](http://datacommons.cyverse.org/browse/iplant/home/shared) data folders are part of the [Data Commons](http://datacommons.cyverse.org/). Unlike CyVerse Curated data, Community Released datasets do not have permanent identifiers and remain under the control of community members. For more information on storing and sharing data in CyVerse, including full definitions of different data types, please see our [Data Policy](http://www.cyverse.org/data-policy) and [Data Commons User Agreement](http://www.cyverse.org/data-commons-user-agreement).

Community Released data folders may contain some private data (visible only to the owner or community members), but the bulk of the data should be public.

Individuals or groups can request Community Released data folders, but at least one CyVerse user must be specified as an owner.

Community Released data folders must include metadata describing the contents. Before submitting your request, see the wiki page on [Preparing Community Released Data Folders](https://wiki.cyverse.org/wiki/display/DC/Preparing+Community+Released+Data+Folders).', '1574511', 'true') ON CONFLICT ("id") DO NOTHING;

-- api_formsection
INSERT INTO public.api_formsection ("id", "name", "created_at", "updated_at", "form_id", "index", "description") VALUES ('2', 'Project', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '2', '0', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formsection ("id", "name", "created_at", "updated_at", "form_id", "index", "description") VALUES ('3', 'Shared Folder', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '2', '1', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formsection ("id", "name", "created_at", "updated_at", "form_id", "index", "description") VALUES ('4', 'Data Management Plan', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '2', '2', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formsection ("id", "name", "created_at", "updated_at", "form_id", "index", "description") VALUES ('13', 'Request', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '7', '0', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formsection ("id", "name", "created_at", "updated_at", "form_id", "index", "description") VALUES ('14', 'Folder', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '7', '1', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formsection ("id", "name", "created_at", "updated_at", "form_id", "index", "description") VALUES ('15', 'Data Management Plan', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '7', '2', '') ON CONFLICT ("id") DO NOTHING;

-- api_formfield
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('8', 'Project Principal Investigator', 'char', '2017-03-30 12:01:28.796-07', '2018-01-02 14:29:58.772246-07', '2', '0', '', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('9', 'Project Principal Investigator Email', 'email', '2017-03-30 12:01:28.796-07', '2018-01-02 14:30:02.439921-07', '2', '1', '', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('10', 'Project Abstract', 'text', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '2', '2', 'Please provide a title and abstract for your project.', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('11', 'Collaborators', 'text', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '2', '3', 'Please list the full names and CyVerse usernames of other individuals who will need access to the data if it is to be shared with a collaborative group.', 'false', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('12', 'CyVerse Team Member ', 'char', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '2', '4', 'List any contact you have at CyVerse', 'false', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('13', 'Name of Shared Folder', 'text', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '3', '0', 'e.g. "my_shared_folder"; please use letters, numbers, or underscores only', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('14', 'Data Description', 'text', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '3', '1', 'Describe the data format (if applicable), tools used or needed to ingest the data, if metadata are available, etc.', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('15', 'Estimated Maximum Data Storage Needed (in GB)', 'number', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '3', '2', 'Please enter a value less than 10 exobytes (1,000,000,000)', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('16', 'Justification for Increase', 'text', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '3', '3', 'Why do you need your allocation increased? Explain how the data are generated and their size. Please include details like what analyses you will be doing, and the size of data generated from your analyses (e.g. size of intermediate output files that can be deleted, size of files that need to be retained). Someone reading your description should be able to determine whether or not the amount of storage being requested is in line with your analysis needs.', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('17', 'What data will be made publicly available?', 'text', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '3', '4', '', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('18', 'What are the timelines for project completion and data release?', 'text', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '4', '0', '', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('19', 'Where will any public data be stored?', 'text', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '4', '1', 'CyVerse supports open data and open science and provides various mechanisms for publishing and sharing data. We generally do not grant increased allocations to single-researcher projects that do not plan to make their data public. If you do not plan to make any of the data public, please use this field to explain why.', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('20', 'Long-term data storage location', 'text', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '4', '2', 'After data analysis is complete, where will you store any remaining data? Include examples: Compress and store locally, public storage provider such as Amazon, DropBox, NCBI, ENSEMBL, etc. CyVerse cannot provide long-term storage of data that is not being actively analyzed.', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('21', 'I agree to the requirements of the CyVerse Data Policy.', 'boolean', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '4', '3', '', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('65', 'Project Principal Investigator', 'char', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '13', '0', 'Please list the project PI''s full name (if you are not the PI).', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('66', 'Collaborators', 'text', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '13', '1', 'Please list the CyVerse usernames of other individuals who will need access to the data if it is to be shared with a collaborative group.', 'false', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('67', 'CyVerse Team Member', 'char', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '13', '2', 'If applicable, please list any CyVerse team member with whom you have discussed your needs prior to submitting this request.', 'false', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('68', 'Folder Name', 'char', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '14', '0', 'No spaces or special characters', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('69', 'As requestor, are you also the owner of the folder?', 'select', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '14', '1', '', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('70', 'If no, who will be the owner of the folder?', 'char', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '14', '2', 'Please provide their full name, their email, and their CyVerse username', 'false', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('71', 'Data Description', 'text', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '14', '3', 'Describe the contents of the folder, how data were generated, and how they can be used. Also include a description of the community and the work the community is doing.', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('72', 'Data Size Requirements (in GB)', 'char', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '14', '4', 'If data is larger than 100GB total, provide justification for an allocation increase.', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('73', 'What percent of the data will be made public versus private?', 'char', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '15', '0', '', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('74', 'How long do you expect the data to be available through CyVerse?', 'char', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '15', '1', '', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('75', 'What is your long term plan for storing this data?', 'char', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '15', '2', 'Where will you store the data, should there be a need to move them out of the CyVerse Data Store?', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('76', 'What metadata will you include?', 'char', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '15', '3', 'In addition to the required metadata fields, what other metadata are you including to make your data more better understood and more discoverable?', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('77', 'I have reviewed the guidelines for preparing a Community Released data folder and agree to supply required metadata.', 'boolean', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '15', '4', 'Read [guidelines for preparing a Community Released data folder](https://wiki.cyverse.org/wiki/display/DC/Preparing+Community+Released+Data+Folders)', 'true', '') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfield ("id", "name", "type", "created_at", "updated_at", "form_section_id", "index", "description", "is_required", "conversion_key") VALUES ('78', 'I agree to the CyVerse Data Policy and Data Commons User Agreement.', 'boolean', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '15', '5', '', 'true', '') ON CONFLICT ("id") DO NOTHING;

-- api_formfieldoption
INSERT INTO public.api_formfieldoption ("id", "name", "index", "created_at", "updated_at", "form_field_id") VALUES ('1', 'Yes', '0', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '13') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfieldoption ("id", "name", "index", "created_at", "updated_at", "form_field_id") VALUES ('2', 'No', '1', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '13') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfieldoption ("id", "name", "index", "created_at", "updated_at", "form_field_id") VALUES ('31', 'Yes', '0', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '69') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_formfieldoption ("id", "name", "index", "created_at", "updated_at", "form_field_id") VALUES ('32', 'No', '1', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '69') ON CONFLICT ("id") DO NOTHING;

-- api_serviceform (DE->form2, Data Commons->form7)
INSERT INTO public.api_serviceform ("id", "created_at", "updated_at", "form_id", "service_id") VALUES ('3', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '2', '2') ON CONFLICT ("id") DO NOTHING;
INSERT INTO public.api_serviceform ("id", "created_at", "updated_at", "form_id", "service_id") VALUES ('4', '2017-03-30 12:01:28.796-07', '2017-03-30 13:05:56.201-07', '7', '3') ON CONFLICT ("id") DO NOTHING;

-- Advance sequences past the seeded ids.
SELECT pg_catalog.setval('public.api_servicemaintainer_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.api_servicemaintainer), true);
SELECT pg_catalog.setval('public.api_service_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.api_service), true);
SELECT pg_catalog.setval('public.api_accessrequestquestion_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.api_accessrequestquestion), true);
SELECT pg_catalog.setval('public.api_form_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.api_form), true);
SELECT pg_catalog.setval('public.api_formsection_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.api_formsection), true);
SELECT pg_catalog.setval('public.api_formfield_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.api_formfield), true);
SELECT pg_catalog.setval('public.api_formfieldoption_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.api_formfieldoption), true);
SELECT pg_catalog.setval('public.api_serviceform_id_seq', (SELECT COALESCE(MAX(id), 1) FROM public.api_serviceform), true);

COMMIT;
